name: Compliance as Code
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Basic SSH stuff
        run: | 
          mkdir -p ~/.ssh
          echo "dummy file" > ~/.ssh/dummy.txt
          ls ~/.ssh/dummy.txt
          echo "${{ secrets.DEPLOYMENT_SERVER_SSH_PRIVKEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run the SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      # - name: Add to the Known Hosts
      #   run: |
      #     ssh-keyscan -H 20.102.88.75 >> ~/.ssh/known_hosts

      - name: Run Chef Help
        run: docker run --rm -v /home/runner/.ssh:/root/.ssh -v $(pwd):/opt chef/inspec exec https://github.com/dev-sec/linux-baseline -t ssh://azureuser@20.102.88.75 -i /root/.ssh/id_rsa --chef-license accept --reporter json:/opt/inspec-output.json


