name: Compliance as Code
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Install Chef
        uses: actionshub/chef-install@main
      
      - name: Verify Chef Inspec is INstalled or Not
        run: inspec --help

      - name: Scanning our github runner
        run: inspec exec ubuntuhardening --chef-license