name: Compliance as Code
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Basic SSH stuff
        run: | 
          mkdir -p ~/.ssh
          echo "dummy file" > ~/.ssh/dummy.txt
          ls ~/.ssh/dummy.txt
          echo "$DEPLOYMENT_SERVER_SSH_PRIVKEY" | tr -d '\r' > ~/.ssh/id_rsa
        continue-on-error: true

      # - name: Run Chef Help
      #   run: docker run --rm -v $(pwd):/opt chef/inspec --help

