name: Compliance as Code
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Basic SSH stuff
        run: | 
          cd ~/.ssh
          pwd
        continue-on-error: true

      # - name: Run Chef Help
      #   run: docker run --rm -v $(pwd):/opt chef/inspec --help

