name: Compliance as Code
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: install chef
        uses: actionshub/chef-install@main

      - name: Run Chef Inspec
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          inspec exec ubuntuhardening -t ssh://nishanth@20.51.237.143 --password $SERVER_PASSWORD --chef-license accept --reporter json:inspec-output.json

      # - name: copy file via ssh password
      #   uses: appleboy/scp-action@master
      #   env:
      #     PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
      #   with:
      #     host: 20.102.88.75
      #     username: azureuser
      #     key: $PRIVATE_KEY
      #     port: 22
      #     source: "package.json"
      #     target: "/home/nishanth/package.json"

