name: Compliance as Code
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: install chef
        uses: actionshub/chef-install@main

      - name: Run Chef Inspec
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          inspec exec ubuntuhardening -t ssh://nishanth@20.51.237.143 --password $SERVER_PASSWORD --chef-license accept --reporter json:inspec-output.json
        continue-on-error: true

      - name: Upload the Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: inspec-scan-report
          path: inspec-output.json
        if: always()   
