name: Compliance as Code
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Basic SSH stuff
        run: | 
          mkdir -p ~/.ssh
          echo "dummy file" > ~/.ssh/dummy.txt
          ls ~/.ssh/dummy.txt
          echo "${{ secrets.DEPLOYMENT_SERVER_SSH_PRIVKEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 20.102.88.75 >> ~/.ssh/known_hosts
        continue-on-error: true

      # - name: Run Chef Help
      #   run: docker run --rm -v $(pwd):/opt chef/inspec --help

