name: MobileMoney Build and Deployment Workflow
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    #needs: deployment # need
    steps:
      - name: Run Inspec
        run: docker run --rm -v $(pwd):/share chef/inspec --help