name: MobileMoney Build and Deployment Workflow
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    #needs: deployment # need
    steps:
      - name: Updated Packages
        run: sudo apt-get update

      - name: Install inspec
        run: |
          wget https://packages.chef.io/files/stable/inspec/4.18.114/ubuntu/16.04/inspec_4.18.114-1_amd64.deb
          sudo dkpg -i dpkg -i inspec_4.18.114-1_amd64.deb
          inspec --help