name: MobileMoney Build and Deployment Workflow
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    #needs: deployment # need
    steps:
      - name: Updated Packages
        run: sudo apt-get update

      - name: Install inspec
        run: wget https://packages.chef.io/files/stable/inspec/4.18.114/ubuntu/16.04/inspec_4.18.114-1_amd64.deb
      
      - run: sudo dkpg -i dpkg -i inspec_4.18.114-1_amd64.deb
      
      - run: inspec --help

      - name: Configure SSH Keys
        run: mkdir -p ~/.ssh
      
      - run: echo ${{ secrets.DEPLOYMENT_SERVER_SSH_PRIVKEY }} | tr -d '\r' > ~/.ssh/id_rsa
      
      - run: chmod 600 ~/.ssh/id_rsa
      - run: eval "$(ssh-agent -s)"
      - run: ssh-add ~/.ssh/id_rsa
      - run: ssh-keyscan -H ${{ secrets.DEPLOYMENT_SERVER }} >> ~/.ssh/known_hosts

      - name: Scan the Server
        run: inspec exec https://github.com/dev-sec/linux-baseline -t ssh://azureuser@${{ secrets.DEPLOYMENT_SERVER }} -i ~/.ssh/id_rsa --chef-license accept --reporter json:inspec-output.json
      
      - name: Upload the Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: inspec-scan-report
          path: inspec-output.json
        if: always()    