name: MobileMoney Build and Deployment Workflow
on: [push]
jobs:
  inspec-scan:
    runs-on: ubuntu-latest
    #needs: deployment # need
    steps:
      - name: Run Inspec
        run: docker run --rm -v $(pwd):/share chef/inspec --help

      - name: Check Inspec
        run: docker run --rm -v /root/.ssh:/root/.ssh -v $(pwd):/opt chef/inspec exec https://github.com/dev-sec/linux-baseline -t ssh://root@${{DEPLOYMENT_SERVER}} -i /root/.ssh/id_rsa --chef-license accept --reporter json:/opt/inspec-output.json